#!/usr/bin/env bash
# This script displays the content of /etc/passwd with username, user ID, and home directory path
while IFS=':' read -r username _ uid _ _ home _; do
    echo "$username:$uid:$home"
done < /etc/passwd
