#!/usr/bin/env bash
#Write a manage_my_process Bash script that:
#Indefinitely writes I am alive! to the file /tmp/my_process
#In between every I am alive! message, the program should pause for 2 seconds
if [[ "$#" == "1" ]]; then
  if [[ "$1" == "start" ]]; then
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
  elif [[ "$1" == "stop" ]]; then
    if test -f "/var/run/my_process.pid"; then
      kill "$(cat /var/run/my_process.pid)"
    fi
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
  elif [[ "$1" == "restart" ]]; then
    # stop program
    if test -f "/var/run/my_process.pid"; then
      kill "$(cat /var/run/my_process.pid)"
    fi
    # start program
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
  else
    echo "Usage: manage_my_process {start|stop|restart}"
  fi
else
  echo "Usage: manage_my_process {start|stop|restart}"
fi
