#!/usr/bin/env bash
#a Bash script that stops 4-to_infinity_and_beyond process
PROGRAM="4-to_infinity_and_beyond"
PID="$(ps -ef | awk -v file="$PROGRAM" '$NF ~file {print $2}'| tail -n 1)"
kill -15 "$PID"
