#!/usr/bin/env bash
#a Bash script that stops 4-to_infinity_and_beyond process
PROGRAM="4-to_infinity_and_beyond"
PATTERN="$(ps -ef | awk -v file="$PROGRAM" '$NF ~file {print $8}')"
echo "Never run it without making sure that a command is running"
echo "This could cause unusual behaviour when running it again!!!"
pkill -15 "$PATTERN"
